import { MigrationInterface, QueryRunner } from "typeorm";

export class createTables1657821213424 implements MigrationInterface {
    name = 'createTables1657821213424'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "providers" ("id" uuid NOT NULL, "fantasy_name" character varying(256) NOT NULL, "name" character varying(256) NOT NULL, "cnpj" character varying(14) NOT NULL, "ie" character varying(9) NOT NULL, "street" character varying(256) NOT NULL, "number" integer NOT NULL, "complement" character varying(256), "district" character varying(256) NOT NULL, "city" character varying(256) NOT NULL, "state" character varying(2) NOT NULL, "country" character varying(256) NOT NULL, "zip_code" character varying(10) NOT NULL, CONSTRAINT "PK_af13fc2ebf382fe0dad2e4793aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "total_price" numeric(10,2) NOT NULL, "status" character varying(50) NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supply" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(256) NOT NULL, "buy_price" numeric(10,2) NOT NULL, CONSTRAINT "PK_11dcdc2def0eb6d10ed3ae0180d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(256) NOT NULL, "price" numeric(10,2) NOT NULL, "img" character varying NOT NULL, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subtotal" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_c524ec48751b9b5bcfbf6e59be7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cartId" uuid, CONSTRAINT "PK_d9a0835407701eb86f874474b7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "email" character varying(256) NOT NULL, "password" character varying(128) NOT NULL, "isAdm" boolean NOT NULL DEFAULT false, "cartId" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "REL_89502c44bd22c06e714c31c1e9" UNIQUE ("cartId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("id" uuid NOT NULL, "number" integer NOT NULL, "street" character varying(256) NOT NULL, "complement" character varying(256) NOT NULL, "state" character varying(2) NOT NULL, "zip_code" integer NOT NULL, "country" character varying(2) NOT NULL, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock" ("id" uuid NOT NULL, "qtd" integer NOT NULL, "supplyIdId" uuid, CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders_supplies_supply" ("ordersId" uuid NOT NULL, "supplyId" uuid NOT NULL, CONSTRAINT "PK_f33d419e1f6e6c2bb86842ad615" PRIMARY KEY ("ordersId", "supplyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_06685b5d38c88848a25db50a3d" ON "orders_supplies_supply" ("ordersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_11dbae20b89ba71ff1bd500cba" ON "orders_supplies_supply" ("supplyId") `);
        await queryRunner.query(`CREATE TABLE "orders_provider_providers" ("ordersId" uuid NOT NULL, "providersId" uuid NOT NULL, CONSTRAINT "PK_5af17798da5299b858898a1f69f" PRIMARY KEY ("ordersId", "providersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f56f246cf595fac032065f264" ON "orders_provider_providers" ("ordersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c74a55c1e38828a5ec048abb0" ON "orders_provider_providers" ("providersId") `);
        await queryRunner.query(`CREATE TABLE "supply_provider_providers" ("supplyId" uuid NOT NULL, "providersId" uuid NOT NULL, CONSTRAINT "PK_11b0e6945a1a685b8863d8d5fde" PRIMARY KEY ("supplyId", "providersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e0f65057d880a475682b8fd6e0" ON "supply_provider_providers" ("supplyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e8efa67b509d44179bd084e0b" ON "supply_provider_providers" ("providersId") `);
        await queryRunner.query(`CREATE TABLE "supply_orders_orders" ("supplyId" uuid NOT NULL, "ordersId" uuid NOT NULL, CONSTRAINT "PK_585907f522395cec4f3a6fbe527" PRIMARY KEY ("supplyId", "ordersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9e156b794e83d1382baf8c57dd" ON "supply_orders_orders" ("supplyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b46f6c1f080b11c685903a965d" ON "supply_orders_orders" ("ordersId") `);
        await queryRunner.query(`CREATE TABLE "product_supplies_supply" ("productId" uuid NOT NULL, "supplyId" uuid NOT NULL, CONSTRAINT "PK_2b2c2d52b90fe15924c44f014d4" PRIMARY KEY ("productId", "supplyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e65f7d45041da29b0019e83915" ON "product_supplies_supply" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b73f68efbba26c0e5b02655214" ON "product_supplies_supply" ("supplyId") `);
        await queryRunner.query(`CREATE TABLE "cart_products_product" ("cartId" uuid NOT NULL, "productId" uuid NOT NULL, CONSTRAINT "PK_785ab9c1dbede19ef42bf12280b" PRIMARY KEY ("cartId", "productId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6ce39be5d354954a88ded1eba" ON "cart_products_product" ("cartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fc996e42b6330c97f8cffbddf" ON "cart_products_product" ("productId") `);
        await queryRunner.query(`CREATE TABLE "users_address_address" ("usersId" uuid NOT NULL, "addressId" uuid NOT NULL, CONSTRAINT "PK_ad956bc5f1b60a4644d04b2105a" PRIMARY KEY ("usersId", "addressId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6d6222b7cde9489bdce80abbf" ON "users_address_address" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9942798c59c9128aa4d910090a" ON "users_address_address" ("addressId") `);
        await queryRunner.query(`CREATE TABLE "users_tickets_ticket" ("usersId" uuid NOT NULL, "ticketId" uuid NOT NULL, CONSTRAINT "PK_bfa59fada1608773fa6a5ad76c5" PRIMARY KEY ("usersId", "ticketId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4735db8e4eddd953a00c77e33" ON "users_tickets_ticket" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_049aa7a88d56f7bfac1201f6c2" ON "users_tickets_ticket" ("ticketId") `);
        await queryRunner.query(`CREATE TABLE "address_user_id_users" ("addressId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_eb728ba3c61f7d56bb12305813d" PRIMARY KEY ("addressId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbdb6df5dbd572f2bbcf59a008" ON "address_user_id_users" ("addressId") `);
        await queryRunner.query(`CREATE INDEX "IDX_03d7a66df7c2af9567a15e605f" ON "address_user_id_users" ("usersId") `);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "REL_89502c44bd22c06e714c31c1e9"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "cartId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "cartId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_89502c44bd22c06e714c31c1e93" UNIQUE ("cartId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isAdm" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ticket" ADD CONSTRAINT "FK_470e53fb414cf1104837c1b8364" FOREIGN KEY ("cartId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_89502c44bd22c06e714c31c1e93" FOREIGN KEY ("cartId") REFERENCES "cart"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_73259b799fbc3b4902c0441cc46" FOREIGN KEY ("supplyIdId") REFERENCES "supply"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders_supplies_supply" ADD CONSTRAINT "FK_06685b5d38c88848a25db50a3d0" FOREIGN KEY ("ordersId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orders_supplies_supply" ADD CONSTRAINT "FK_11dbae20b89ba71ff1bd500cba9" FOREIGN KEY ("supplyId") REFERENCES "supply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orders_provider_providers" ADD CONSTRAINT "FK_8f56f246cf595fac032065f264d" FOREIGN KEY ("ordersId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orders_provider_providers" ADD CONSTRAINT "FK_7c74a55c1e38828a5ec048abb0d" FOREIGN KEY ("providersId") REFERENCES "providers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "supply_provider_providers" ADD CONSTRAINT "FK_e0f65057d880a475682b8fd6e0f" FOREIGN KEY ("supplyId") REFERENCES "supply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "supply_provider_providers" ADD CONSTRAINT "FK_4e8efa67b509d44179bd084e0b3" FOREIGN KEY ("providersId") REFERENCES "providers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "supply_orders_orders" ADD CONSTRAINT "FK_9e156b794e83d1382baf8c57dd0" FOREIGN KEY ("supplyId") REFERENCES "supply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "supply_orders_orders" ADD CONSTRAINT "FK_b46f6c1f080b11c685903a965da" FOREIGN KEY ("ordersId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_supplies_supply" ADD CONSTRAINT "FK_e65f7d45041da29b0019e83915c" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_supplies_supply" ADD CONSTRAINT "FK_b73f68efbba26c0e5b02655214b" FOREIGN KEY ("supplyId") REFERENCES "supply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cart_products_product" ADD CONSTRAINT "FK_e6ce39be5d354954a88ded1ebac" FOREIGN KEY ("cartId") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cart_products_product" ADD CONSTRAINT "FK_0fc996e42b6330c97f8cffbddfa" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_address_address" ADD CONSTRAINT "FK_a6d6222b7cde9489bdce80abbf9" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_address_address" ADD CONSTRAINT "FK_9942798c59c9128aa4d910090aa" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_tickets_ticket" ADD CONSTRAINT "FK_c4735db8e4eddd953a00c77e336" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_tickets_ticket" ADD CONSTRAINT "FK_049aa7a88d56f7bfac1201f6c27" FOREIGN KEY ("ticketId") REFERENCES "ticket"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "address_user_id_users" ADD CONSTRAINT "FK_fbdb6df5dbd572f2bbcf59a0088" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "address_user_id_users" ADD CONSTRAINT "FK_03d7a66df7c2af9567a15e605fd" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "address_user_id_users" DROP CONSTRAINT "FK_03d7a66df7c2af9567a15e605fd"`);
        await queryRunner.query(`ALTER TABLE "address_user_id_users" DROP CONSTRAINT "FK_fbdb6df5dbd572f2bbcf59a0088"`);
        await queryRunner.query(`ALTER TABLE "users_tickets_ticket" DROP CONSTRAINT "FK_049aa7a88d56f7bfac1201f6c27"`);
        await queryRunner.query(`ALTER TABLE "users_tickets_ticket" DROP CONSTRAINT "FK_c4735db8e4eddd953a00c77e336"`);
        await queryRunner.query(`ALTER TABLE "users_address_address" DROP CONSTRAINT "FK_9942798c59c9128aa4d910090aa"`);
        await queryRunner.query(`ALTER TABLE "users_address_address" DROP CONSTRAINT "FK_a6d6222b7cde9489bdce80abbf9"`);
        await queryRunner.query(`ALTER TABLE "cart_products_product" DROP CONSTRAINT "FK_0fc996e42b6330c97f8cffbddfa"`);
        await queryRunner.query(`ALTER TABLE "cart_products_product" DROP CONSTRAINT "FK_e6ce39be5d354954a88ded1ebac"`);
        await queryRunner.query(`ALTER TABLE "product_supplies_supply" DROP CONSTRAINT "FK_b73f68efbba26c0e5b02655214b"`);
        await queryRunner.query(`ALTER TABLE "product_supplies_supply" DROP CONSTRAINT "FK_e65f7d45041da29b0019e83915c"`);
        await queryRunner.query(`ALTER TABLE "supply_orders_orders" DROP CONSTRAINT "FK_b46f6c1f080b11c685903a965da"`);
        await queryRunner.query(`ALTER TABLE "supply_orders_orders" DROP CONSTRAINT "FK_9e156b794e83d1382baf8c57dd0"`);
        await queryRunner.query(`ALTER TABLE "supply_provider_providers" DROP CONSTRAINT "FK_4e8efa67b509d44179bd084e0b3"`);
        await queryRunner.query(`ALTER TABLE "supply_provider_providers" DROP CONSTRAINT "FK_e0f65057d880a475682b8fd6e0f"`);
        await queryRunner.query(`ALTER TABLE "orders_provider_providers" DROP CONSTRAINT "FK_7c74a55c1e38828a5ec048abb0d"`);
        await queryRunner.query(`ALTER TABLE "orders_provider_providers" DROP CONSTRAINT "FK_8f56f246cf595fac032065f264d"`);
        await queryRunner.query(`ALTER TABLE "orders_supplies_supply" DROP CONSTRAINT "FK_11dbae20b89ba71ff1bd500cba9"`);
        await queryRunner.query(`ALTER TABLE "orders_supplies_supply" DROP CONSTRAINT "FK_06685b5d38c88848a25db50a3d0"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_73259b799fbc3b4902c0441cc46"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_89502c44bd22c06e714c31c1e93"`);
        await queryRunner.query(`ALTER TABLE "ticket" DROP CONSTRAINT "FK_470e53fb414cf1104837c1b8364"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isAdm" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(128) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_89502c44bd22c06e714c31c1e93"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "cartId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "cartId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "REL_89502c44bd22c06e714c31c1e9" UNIQUE ("cartId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03d7a66df7c2af9567a15e605f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbdb6df5dbd572f2bbcf59a008"`);
        await queryRunner.query(`DROP TABLE "address_user_id_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_049aa7a88d56f7bfac1201f6c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4735db8e4eddd953a00c77e33"`);
        await queryRunner.query(`DROP TABLE "users_tickets_ticket"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9942798c59c9128aa4d910090a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6d6222b7cde9489bdce80abbf"`);
        await queryRunner.query(`DROP TABLE "users_address_address"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fc996e42b6330c97f8cffbddf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6ce39be5d354954a88ded1eba"`);
        await queryRunner.query(`DROP TABLE "cart_products_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b73f68efbba26c0e5b02655214"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e65f7d45041da29b0019e83915"`);
        await queryRunner.query(`DROP TABLE "product_supplies_supply"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b46f6c1f080b11c685903a965d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e156b794e83d1382baf8c57dd"`);
        await queryRunner.query(`DROP TABLE "supply_orders_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e8efa67b509d44179bd084e0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0f65057d880a475682b8fd6e0"`);
        await queryRunner.query(`DROP TABLE "supply_provider_providers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c74a55c1e38828a5ec048abb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f56f246cf595fac032065f264"`);
        await queryRunner.query(`DROP TABLE "orders_provider_providers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11dbae20b89ba71ff1bd500cba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06685b5d38c88848a25db50a3d"`);
        await queryRunner.query(`DROP TABLE "orders_supplies_supply"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "ticket"`);
        await queryRunner.query(`DROP TABLE "cart"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "supply"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "providers"`);
    }

}
